name: Docker Image CI

# 触发条件
# 在push至master分支触发
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    # 运行的容器
    runs-on: ubuntu-latest
    
    steps:
    # 切换分支
    - uses: actions/checkout@v4.1.1

    # 获取版本信息
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})

    # 虚拟化技术，适配不同内核
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    # 登录Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 编译镜像
    - name: Build the Docker image and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        tags: ${{ secrets.DOCKER_USERNAME }}/60s-today:latest
















